### ISSUE TITLE
Character view freaks out in portrait mode on phone

### ISSUE THREAD

**Issue by wffurr** [madcowfred/evething#108]
![screenshot_2015-11-04-08-52-42](https://cloud.githubusercontent.com/assets/519506/10939710/ae6008a8-82d1-11e5-9f04-82b89cd04cb8.png)

The menu sidebar continually flashes in and out of place when scrolling while viewing an individual character.

Chrome 46 on Android 5.1.1.

**Comment by atkinsj** [comment]
+1ing this -- this is a significant issue for me on a phone. Repeatable on Chrome 48 on an iPhone 6s.
