### ISSUE TITLE
Hosted version at evething.org needs a new database dump

### ISSUE THREAD

**Issue by wffurr** [madcowfred/evething#112]
I'm training Command Destroyers IV and my queue shows Recon Ships IV at -37.7% instead.

![missing command ships](https://cloud.githubusercontent.com/assets/519506/12080901/08c12cb0-b238-11e5-961f-255d0fc87837.PNG)

**Comment by Gillingham** [comment]
Updated the data dump to the latest (from 2016-01-12)
