### ISSUE TITLE
Importing latest sqlite dump results in foreign key constraint violation

### ISSUE THREAD

**Issue by zerfall** [madcowfred/evething#117]
Using the sqlite dump available from [here](https://www.fuzzwork.co.uk/dump/sqlite-latest.sqlite.bz2) and running importy.py results in the following error:

django.db.utils.IntegrityError: insert or update on table "thing_blueprintcomponent" violates foreign key constraint "item_id_refs_id_c02444b0"
DETAIL:  Key (item_id)=(41302) is not present in table "thing_item".

**Comment by skyride** [comment]
I just deleted the offending foreign key and that seemed to do the job.

**Comment by Gillingham** [comment]
:ccp: created all the new ammo types and they point to marketGroup id 2155, coincidentally that doesn't exist the data dump.
Easy to ignore those blueprints, but uh no idea why the damn marketgroup doesn't exist.

**Comment by Gillingham** [comment]
This got fixed awhile ago
