### ISSUE TITLE
In EventLog, owner of completed/expired order is wrong.

### ISSUE THREAD

**Issue by ghost** [madcowfred/evething#17]
For corp orders, it should be `[CORP] wallet` instead of director name.

**Comment by madcowfred** [comment]
The 'Source' column is where the order came from. The /corp/IndustryJobs API does not return a wallet division so the best information I can give you is [CORP] :(

**Comment by ghost** [comment]
Your're right.
[CORP] and maybe manufacturer name would be awesome

**Comment by ghost** [comment]
Oups I think we missposted, These 2 comments should be in #18.

**Comment by madcowfred** [comment]
I got rather muddled about what this was referring to, oops.
