### ISSUE TITLE
Wallet Journal filtering - defined date range support

### ISSUE THREAD

**Issue by Darkstryke** [madcowfred/evething#19]
I know there is a "# of days _____" option right now, but would you consider the ability to add time-stamped date range filtering? It would make doing finance reporting much easier if you happen to forget to do it on an exact date (like end of month, or end of week, etc).

Awesome tool regardless of my nitpick!

**Comment by madcowfred** [comment]
Implemented in b9097ba4 - also for Transactions because hey why not.
