### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by hreeder** [madcowfred/evething#2]
When running the importer to grab the data from the eve sde, I get the following:

> python import.py
> => Region:
> Traceback (most recent call last):
>   File "import.py", line 808, in <module>
>     importer.import_all()
>   File "import.py", line 67, in import_all
>     time_func('Region', self.import_region)
>   File "import.py", line 57, in time_func
>     added = f()
>   File "import.py", line 106, in import_region
>     Region.objects.bulk_create(new)
> AttributeError: 'Manager' object has no attribute 'bulk_create'

EveThing database: MySQL
EvE SDE: Sqlite3 (Inf12)
OS: Ubuntu Server 12.04
Python 2.7.3
Django 1.3.1

Running latest version of code from the develop branch

**Comment by madcowfred** [comment]
> Django 1.3.1

Django 1.4 is required due to liberal misuse of bulk_create() and prefetch_related()

**Comment by hreeder** [comment]
Ah cheers - It seems the package in the ubuntu repositories is out of date then.
