### ISSUE TITLE
EVE Mail viewer

### ISSUE THREAD

**Issue by SwimlanesOnline** [madcowfred/evething#23]
Can you implement a viewer for eve mails? That would be great.

**Comment by operinko** [comment]
Keep an eye on my fork, I'm planning on creating one soonish :)

**Comment by madcowfred** [comment]
I really need to add some code to mitigate some of the abject stupidity of CCP's recent API changes first, after that's done I'll look at doing mails/notifications :octopus:

**Comment by madcowfred** [comment]
Implemented and appears to work.
