### ISSUE TITLE
Missing less file "font-awesome/font-awesome.less" according to bootstrap.less

### ISSUE THREAD

**Issue by Kyria** [madcowfred/evething#24]
Hello,

In bootstrap.less you have this line : 
    @import "font-awesome/font-awesome.less";

but it seems there's no "font-awesome" directory and no "font-awesome.less" in the project.

Any way fixing this instead of just commenting the line ?

I hope i'm not just blind and didn't see the correct way to fix it...

**Comment by Kyria** [comment]
Found why it's missing : it's just an external lib from https://github.com/FortAwesome/Font-Awesome. No need to keep this ticket open. 

It might be interesting to add this for devs as a "package to get" when installing the app and when we use the less files.

**Comment by madcowfred** [comment]
You're the first person to ever actually brave the horrors of messing with the JS/LESS. Apparently I forgot to add the files to git, fixed in 4b54400 :octopus:
