### ISSUE TITLE
Missing bootstrap.js for debug mode in /static/js

### ISSUE THREAD

**Issue by Kyria** [madcowfred/evething#25]
In template/base.html you have this javascript call at line 128 :
`<script src="{{ STATIC_URL}}js/bootstrap.js"></script>`

but it seems you didn't put the bootstrap.js file into /static/js/. 

edit: yes, it's only for debug mode. So it doesn't really matter until we need to re-combine and minify javascripts.

Regards,

**Comment by madcowfred** [comment]
The bootstrap.js file is rarely modified since it's just the used js/bootstrap-*.js files concatenated together. Run 'make all' (or 'gmake all' if your make is not GNU make) to build static files properly. I've added the current bootstrap.js to git in 720431c so it works without that step.

**Comment by Kyria** [comment]
ow... my bad. I didn't even notice that the makefile was use to make the statics (as it was not mentioned in the doc, I didn't check it...)

Anyway, thx for at least telling me about 'make all' for static files, and for bootstrap.js.
