### ISSUE TITLE
python-memcached missing from requirements.txt

### ISSUE THREAD

**Issue by jaknel** [madcowfred/evething#31]

**Comment by Gillingham** [comment]
It's still technically optional, though you have to comment out the cache settings.

**Comment by Gillingham** [comment]
What I should actually say is that it really is optional, and excluding it from requirements goes along with not including a specific celery MQ subpackage, or a specific database package. With those two and this the choice of backend is up to the user. So it's up to you to decide what to use and install what you want accordingly.

That said we could use some better documentation on that, leaving this open to remind me of that.

**Comment by Gillingham** [comment]
I added an commented out line to use the DummyCache to the local_settings.example for if people don't want to install memcache.
