### ISSUE TITLE
Debug = False

### ISSUE THREAD

**Issue by MatadorPants** [madcowfred/evething#32]
So, everything works fine as long as Debug = True, but as soon as I switch it to Debug = False, it gives me Page Unavailable: http://puu.sh/4zR6w.png

Literally nothing is changing.. just switching the debug flag. It still starts up fine, just gives that error when navigating to the page. 

Any ideas?

**Comment by madcowfred** [comment]
Add yourself to the ADMINS = block in your local_settings.py "('Bob', 'bob@example.com')", Django will then email you a traceback. You can probably also find it in your Apache logs somewhere but I can never remember where :sheep:

**Comment by MatadorPants** [comment]
I have my email in there, but haven't been getting tracebacks. Checking
through some apache logs to try and find it.

**Comment by madcowfred** [comment]
Interesting. You should also check your mail log to see if there's an issue with sending the email, you may need to mess with some of the [Django settings](https://docs.djangoproject.com/en/dev/ref/settings/) - I've had to use SERVER_EMAIL and the various EMAIL_\* settings occasionally.

**Comment by MatadorPants** [comment]
First thing I checked was the mail log. When refreshing the page and
getting the error, I don't see anything hit the mail log. I'll look into
the Django settings and see what I can find. Thanks.

**Comment by Gillingham** [comment]
Is ALLOWED_HOSTS set to a the proper value? @madcowfred is bad and still hasn't added it to local_settings.example

**Comment by MatadorPants** [comment]
This is my first experience with Django, but I added:

```
ALLOWED_HOSTS = (
    'xxx.xx.xxx.xx' (external IP I'm connecting to)
)
```

And that did not make a difference. Console is still showing "GET / HTTP/1.1" 500 364.

Also tried setting it to '*' and nothing changed.

EDIT: Also, the settings should be fine, right? It works 100% when Debug = True, and only errors when I change Debug to False.

**Comment by Kyria** [comment]
Had the same problem. I just fixed it by adding this line to my local_settings.py (btw, I know \* is not a good solution for production, but it's not prod for me yet):
    ALLOWED_HOSTS = ['*'] 

it's not a tuple "()" you should use with this conf, but a list "[]" (according to https://docs.djangoproject.com/en/1.5/ref/settings/#std%3asetting-ALLOWED_HOSTS ) maybe that's why it didn't make any differences

**Comment by MatadorPants** [comment]
Ah, didn't notice that ALLOWED_HOSTS used [] whereas most the other configs used (). I'll try this shortly and report back.

Thanks.

**Comment by Kyria** [comment]
Hmm, after editing my local_settings, I have again that http 500. 
I edited STATIC_ROOT (not only) but looks like if the path is not good, it does the error too
IMO, further investigation are required... i'll try later again

**Comment by MatadorPants** [comment]
Yeah, changed to 

```
ALLOWED_HOSTS = ['*']
```

and it did not resolve the problem. Still seeing the 500 error.

**Comment by MatadorPants** [comment]
After messing around with some settings and changing STATIC_ROOT, I can get the page to load, but with no CSS.

If DEBUG = True, then static/css/theme-default.min.css returns the correct file. 

If DEBUG = False, then static/css/theme-default.min.css can't be found. It's still looking in the same place for it (ipaddress:port/static/css/theme-default.min.css) but can't be found when set to False.

**Comment by Gillingham** [comment]
You should probably read up on handling static files in django, this is not an evething issue anymore.

**Comment by Kyria** [comment]
As far as I can see (and from research) you cannot use django as "static file server" with a production environment (aka DEBUG=False) you just need to put your static files where a webserver (apache for example) can see them so you can use those files with your django app. ([How To](https://docs.djangoproject.com/en/1.5/howto/static-files/))

I just tried, I don't get anymore bugs like that. It might resolve your problem too. 

Hope it helps :)

**Comment by narthollis** [comment]
A quick note:

`ALLOWED_HOSTS` should contain a list of the host names that django will respond to requests for.

Eg. if you are hosting your EVEthing as `evething.example.com` your would use `ALLOWED_HOSTS = ['evething.example.com']`

**Comment by Gillingham** [comment]
This is more a configuration issue than a problem with evething so closing. I'll add the ALLOWED_HOSTS = [] to the local_settings.py and a link to the django docs shortly to help prevent this in the future.
