### ISSUE TITLE
Python version question

### ISSUE THREAD

**Issue by AMoo** [madcowfred/evething#4]
More a question than an issue but I would like to know why you've written this for Python 2.7 ro more specifically what features of 2.7 are required.

I've been playing around with this on a RPi and it works fine but my main box has CentOS 6 on it which only has v2.6 python.  I'm having no luck getting 2.7 on this box so I wonder if there's any way I can get this to work with 2.6

**Comment by madcowfred** [comment]
2.7 has been out for over 2 years at this point, I'd mostly just hoped I could be lazy about using OrderedDict. I've just added support for the ordereddict module in d9ce00d66920c5cc4af3da325dd3a41659cd9904, try installing it with 'pip install ordereddict' and updating git.

**Comment by AMoo** [comment]
Thanks I'll give it a try.

**Comment by AMoo** [comment]
Support for OrderedDict gets this to run on 2.6.6.  Cdecimal also allows 2.6 users to convert float to decimals.

The installation goes OK and you can get the main page up.  Incidentally I notice the admin area has no theme and the icons are linked to /static/admin/{file} but there's no /static/admin directory.

e: use of total_seconds() is 2.7 only :(

**Comment by madcowfred** [comment]
The admin missing theming is probably because I, er, forgot some steps in the installation docs. You're meant to make a static/ directory in the site root and then run 'python manage.py collectstatic', this copies over the EVEthing static files along with the Django admin files. Updated the README.

**Comment by madcowfred** [comment]
Added thing.stuff.total_seconds function for 2.6 compatibility in 6b15fb923cd2395fe991c4c2e29ec8d13e8cf261, this seems to make things actually work now.
