### ISSUE TITLE
Partially trained skills in skill plans dont work

### ISSUE THREAD

**Issue by Gillingham** [madcowfred/evething#45]
Have a partially trained skill be in a skill plan but not currently training, the skill plan will show the full length of the train for that skill regardless of how many SP you have in it.

**Comment by Kyria** [comment]
You can find a solution here, as I did it in the pull request I submitted, if you want to correct it earlier : https://github.com/Kyria/evething/blob/develop/thing/views/character.py#L454-L460 
https://github.com/Kyria/evething/blob/develop/thing/views/character.py#L486-L491
https://github.com/Kyria/evething/blob/develop/templates/thing/character_skillplan.html#L81-L100
