### ISSUE TITLE
Trade and orders when Character is on char & corp API

### ISSUE THREAD

**Issue by Kyria** [madcowfred/evething#48]
I've got this issue : one of my char is a director for his own corp. I have these API in evething : 
- 1 char API (all access)
- 1 corp API (all access)

If I add the corp API after the char API in evething : all my orders / trade history "disappear" from evething 
If I add the char API after the corp API : I see these orders, but the character is linked to the corp API.

**Comment by Kyria** [comment]
_Maybe this is the solution (I can't test it right now so I hope I don't say any crap)_

At the moment, you have this piece of code in some pages (assets for example): 

``` python
characters = Character.objects.filter(
    apikeys__user=request.user,
    apikeys__valid=True,
).exclude(
    apikeys__key_type=APIKey.CORPORATION_TYPE,
).distinct()
```

It seems that, every time a character has 2 API with one corp API, the exclude statement removes definitely the character from the results. 

A simple correction could be to change the above queryset with this one : 

``` python
characters = Character.objects.filter(
    apikeys__user=request.user,
    apikeys__valid=True,
    apikeys__key_type__in=[APIKey.ACCOUNT_TYPE, APIKey.CHARACTER_TYPE],
).distinct()
```

So instead of excluding all char with that might have a corp API (with others) we are only including those with CHAR/ACCOUNT API.

But I still don't get why, if we add the char API **after** the corp API, this is not an issue, but some corp informations (such as Industry) will not be available after...

**Comment by Gillingham** [comment]
Confirming this fixes an issue with Contracts and stuff, but still trying to figure out exactly stuff went wrong.

When Corp keys get added the Character that is the CEO/whatever is also stored, so I'm thinking because there's a Corp API key with that Character tied to it, it then gets removed from the character list due to that exclude.

Keeping this open until I diagnose further and commit fixes
