### ISSUE TITLE
mapRegions table?

### ISSUE THREAD

**Issue by smickles** [madcowfred/evething#49]
While working on getting this up and running to have my own look at it, I've gotten stuck at:

```
python import.py
```

it returns 

```
django.db.utils.DatabaseError: no such table: mapRegions
```

what, in my own idiocy, did i miss?

**Comment by Gillingham** [comment]
The syncdb/migration steps is what I would assume.

**Comment by smickles** [comment]
from what I can tell, the syncdb and migrate commands worked just fine

**Comment by smickles** [comment]
Starting over from scratch, I see no indication of errors and mapRegions is never created

**Comment by madcowfred** [comment]
You're probably not using the develop branch, or reading the develop branch instructions.

**Comment by smickles** [comment]
I am using the dev branch, and following the dev branch instructions.

What is this supposed to be importing from? I cant figure out what db this is supposed to be connecting to to get the region, constellation ... etc data

**Comment by narthollis** [comment]
The DB you are connecting to for the import is the static EVE data dump. Partially a copy of the SQLite version from http://www.fuzzwork.co.uk/dump/

You may need to update the path for the 'import' database in your local_settings.py file.

**Comment by smickles** [comment]
@narthollis this was definitely the issue.

Thank you all.
