### ISSUE TITLE
Postgresql auto-lowercasing some things

### ISSUE THREAD

**Issue by smickles** [madcowfred/evething#50]
So, I was using sqlite, but import.py generates queries which return over 1000 items and the standard install of sqlite apparently had a magic number limit there ( see http://stackoverflow.com/questions/7106016/too-many-sql-variables-error-in-django-witih-sqlite3 ). I didn't want to recompile sqlite so I switched to postgresql. Got a bunch of errors, but read http://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS and fixed it

**Comment by Gillingham** [comment]
What version of postgres are you using/other versions of things like django etc?

The evething I have running uses postgres and the import worked fine.

**Comment by smickles** [comment]
postgres (PostgreSQL) 9.3.4
amqp (1.4.5)
anyjson (0.3.3)
billiard (3.3.0.17)
celery (3.1.11)
Django (1.6.5)
django-celery (3.1.10)
django-mptt (0.6.1)
jingo (0.7)
Jinja2 (2.7.2)
kombu (3.0.16)
MarkupSafe (0.23)
ordereddict (1.1)
pip (1.4.1)
psycopg2 (2.5.3)
python-memcached (1.53)
pytz (2014.3)
requests (2.3.0)
setuptools (0.9.8)
South (0.8.4)
Unipath (1.0)
wsgiref (0.1.2)

let me know if i missed anything useful :)

**Comment by Gillingham** [comment]
Can you share the errors you got before the fix?

**Comment by smickles** [comment]
```
Programming Error: relation "mapRegions" does not exist
```

This was the only error. It would do that for each table with an uppercase letter until I double quoted it out, and it's from my memory, not copy/pasted, sorry about that, since I had fixed the issue for myself, I selfishly didn't think of keeping a copy of the error or putting it in my OP ~-_-/~

**Comment by Gillingham** [comment]
I'm just finding this odd since I just did a new install for development and used the sqlite database export, and the import.py script worked fine.

This will have to get tested to make sure it doesn't break sqlite/mysql imports before getting commited

**Comment by Gillingham** [comment]
Yea I've now done import with the latest sqlite dump just fine on 4 different systems and am failing to encounter any issues.
What version of python are you using?

**Comment by smickles** [comment]
Python 2.7.5

**Comment by smickles** [comment]
http://www.sqlite.org/limits.html see number 9

How were you able to use sqlite? The query for constellations exceeds this limit.

**Comment by smickles** [comment]
From a fresh install using fuzzwork's sqlite db https://gist.github.com/smickles/032b2f61f4bcd8ae8d00

**Comment by Gillingham** [comment]
Did you complete reset (drop/create) then syncdb + migrate the DB prior to doing this?

**Comment by smickles** [comment]
I did, a whole new virtualenv and everything

**Comment by Gillingham** [comment]
As of Django 1.7 only Postgresql 9.4 and newer are supported so I'm closing this unless you can duplicate this. Since I've been doing a bunch of docker stuff I haven't encountered it.
