### ISSUE TITLE
The Docker build system cannot upgrade the static data dump without wiping the database

### ISSUE THREAD

**Issue by robhaswell** [madcowfred/evething#73]
The current build system primes the data dump as part of first-run initialization. The database is also created at this point.

These two processes should be separated so that the EVE static data dump can be refreshed without going through database initialization.

**Comment by Gillingham** [comment]
I don't know why you say they aren't separated. Updating the static data dump you simply re-run the import script. You do not need to re-run syncdb.

**Comment by robhaswell** [comment]
This is a missing improvement for PR https://github.com/madcowfred/evething/pull/71

**Comment by Gillingham** [comment]
You don't need to open issues here for changes to a pull request that hasn't been merged. Any changes you make to your branch will be reflected in that pull request, if you need issue tracking it makes more sense to do the issues on your fork or just in commits.

**Comment by robhaswell** [comment]
Will do.
