### ISSUE TITLE
Develop is the master branch

### ISSUE THREAD

**Issue by robhaswell** [madcowfred/evething#74]
The de-facto master branch for this project is `develop`. This can be represented in GitHub through use of the `Settings` screens.

Setting a correct master branch will reduce the opportunity for confusion and error when visiting the project, checking out the repository, or submitting pull requests.

**Comment by Gillingham** [comment]
@madcowfred You should probably do this since I don't have permissions

**Comment by madcowfred** [comment]
Oh yeah, I forgot to ever actually do this. Done.
