### ISSUE TITLE
URLs with spaces are not recognised over fastcgi

### ISSUE THREAD

**Issue by robhaswell** [madcowfred/evething#88]
When setting up evething using `nginx` with the `fastcgi_pass` option, spaces in character names result in 404 errors. For example:

nginx.conf:

```
    location / {
        include fastcgi_params;
        fastcgi_pass fig_web_1:8080;
    }
```

evething launched with:

```
/usr/local/bin/python /opt/evething/manage.py runfcgi host=0.0.0.0 port=8080
```

Results in:

![screen shot 2014-10-06 at 17 06 38](https://cloud.githubusercontent.com/assets/415486/4528878/cba9f814-4d72-11e4-908b-4d16a8123af2.png)

All other functions in this particular installation seem to work.

**Comment by Gillingham** [comment]
I'm going to wager this isn't an evething issue and likely incorrect configuration on your end. evethings been working using mod_wsgi, uwsgi, etc using a variety of webserver configurations. Having just one specific setup not work while everything else is fine makes me think that one specific setup is broken.

**Comment by robhaswell** [comment]
I considered that before filing this ticket, but according to all sources this is The Way that you set up Django and Nginx over fastcgi.

At very least this is a documentation issue.

**Comment by Gillingham** [comment]
Unless you want to look into this more I'm closing this. I don't really want to setup this all to check, but I'm using uwsgi and nginx just fine, so maybe use that instead if you don't want to investigate.

**Comment by MichaelErmer** [comment]
@robhaswell this does the magic.

```
   location / {
        fastcgi_param PATH_INFO $fastcgi_script_name;
        #include fastcgi_params;
        fastcgi_pass compose_web_1:8080;
    }
```

**Comment by robhaswell** [comment]
Great! Thanks @MichaelErmer. This will probably encourage me to fix this.

**Comment by Gillingham** [comment]
I would still strongly recommend using uwsgi over fastcgi, every benchmark I've seen it comes out rather far ahead. If you don't like that gunicorn and nginx proxing will also be faster than fastcgi.
