### ISSUE TITLE
Django-celery issues.

### ISSUE THREAD

**Issue by Natsui31** [madcowfred/evething#90]
Hello, i'm having an issue about apache.

[Wed Dec 03 04:47:35 2014] [error] [client 127.0.0.1] ImportError: No module named djcelery
[Wed Dec 03 04:47:35 2014] [error] [client 127.0.0.1]     import djcelery

After checking, Django-Celery was not on my virtual environment who caused an Error 500.

**Comment by Gillingham** [comment]
Sounds like you didn't install celery correctly.
